- id: arxiv:2510.01925
  title: "Enhancing Large Language Model Reasoning with Reward Models: An Analytical Survey"
  authors: 
  - Qiyuan Liu
  - Hao Xu
  - Xuhong Chen
  - Wei Chen
  - Yee Whye Teh
  - Ning Miao
  date: 2025-10-03
  publisher: arXiv
  link: https://arxiv.org/abs/2510.01925
  image: images/publication/enhancing large language model reasoning.png       

- id: arxiv:2601.04537
  title: "Not All Steps are Informative: On the Linearity of LLMs' RLVR Training"
  authors: 
  - Tianle Wang
  - Zhongyuan Wu
  - Shenghao Jin
  - Hao Xu
  - Wei Chen
  - Ning Miao
  date: 2026-01-25
  publisher: arXiv
  link: https://arxiv.org/abs/2601.04537
  buttons:
    - type: source
      text: Code
      link: https://github.com/Miaow-Lab/RLVR-Linearity
  image: images/publication/not all steps are informative.png

